<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Sản phẩm nổi bật</h3></div>
        <div class="panel-body">
            <?php echo $this->partial('home/partial/product-item', array('products' => $productHots)); ?>
        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Sản phẩm mới</h3></div>
        <div class="panel-body">
            <?php echo $this->partial('home/partial/product-item', array('products' => $productNews)); ?>

        </div>
    </div>
</div>