<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<?php echo $this->partial('admin/partial/button_add', array('moduleName' => $module, 'urlOther' => $this->url('admin/' . $module, array('action' => 'add'), array('query' => array('group_template_id' => $_GET['group_template_id']))))); ?>

<?php echo $this->partial('admin/partial/message'); ?>

    <div class="box">
        <div class="box-title">
            <h3><i class="icon-edit"></i> <?php echo $groupTemplate['group_template_name']; ?></h3>
        </div>
    </div>

<form name="" id="frm" action="<?php echo $this->url('admin/' . $module); ?>" method="post">
    <input type="hidden" name="group_template_id" value="<?php echo $_GET['group_template_id'];?>">
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th><input type="checkbox" class="checkbox-all" /></th>
                        <th>Tên</th>
                        <th>Giao diện</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr style="background: <?php echo $statusColor[$record['status']]; ?>">
                            <td><input type="checkbox" class="checkbox-item" name="check_item[]" value="<?php echo $record['template_id']; ?>" /></td>
                            <td><strong><?php echo $this->escapeHtml($record['template_name']); ?></strong></td>
                            <td><strong><?php echo $this->escapeHtml($record['group_template_name']); ?></strong></td>
                            <td><?php echo $status[$record['template_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/' . $module, array('action' => 'edit'), array('query' => array('id' => $record['template_id'], 'group_template_id' => $_GET['group_template_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/' . $module, array('action' => 'delete'), array('query' => array('id' => $record['template_id'], 'group_template_id' => $_GET['group_template_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/' . $module),)); ?>
                </div>

            </div>
        </div>
    </div>
</div>
</form>

<?php echo $this->partial('admin/partial/action_list'); ?>