<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('cms/css/themes.css'))
        ->prependStylesheet($this->basePath('cms/css/style.css'))
        ->prependStylesheet($this->basePath('cms/css/bootstrap-responsive.min.css'))
        ->prependStylesheet($this->basePath('cms/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('cms/js/eakroko.js'))
        ->prependFile($this->basePath('cms/js/bootstrap.min.js'))
        ->prependFile($this->basePath('cms/js/jquery.min.js'))
    ; ?>

</head>

<body class='login'>
<div class="wrapper">
    <h1><a href="index.html"><img src="<?php echo $this->basePath('cms/img/logo-big.png');?>" alt="" class='retina-ready' width="59" height="49">CMS</a></h1>
    <div class="login-body">
        <?php echo $this->content; ?>
    </div>
</div>

</body>

</html>
