<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('cms/css/themes.css'))
        ->prependStylesheet($this->basePath('cms/css/style.css'))
        ->prependStylesheet($this->basePath('cms/css/bootstrap-responsive.min.css'))
        ->prependStylesheet($this->basePath('cms/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('cms/js/eakroko.js'))
        ->prependFile($this->basePath('cms/js/bootstrap.min.js'))
        ->prependFile($this->basePath('cms/js/jquery.min.js'))
    ; ?>

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger" style="margin: 20px;">
                    <h4>Có lỗi!</h4>
                    <?php echo $this->message;?>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
