<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Chi tiết sản phẩm</h3></div>
        <div class="panel-body">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <img  width="100%" style="cursor: pointer" class="img-thumbnail" data-toggle="modal" data-target=".bs-example-modal-lg"
                     src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture'];?>&w=270&h=270"
                     alt="post image">
            </div>

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8" style="padding-left: 15px;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h3 style="margin-top: 5px; margin-bottom: 0"><?php echo $this->escapeHtml($product['product_name']);?></h3>
                        <br>
<!--                        <p>Mã sản phẩm: --><?php //echo $this->escapeHtml($product['product_code']);?><!--</p>-->
                        <?php echo $product['product_description'];?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Sản phẩm cùng loại</h3></div>
        <div class="panel-body">
            <?php echo $this->partial('home/partial/product-item', array('products' => $productsOther)); ?>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <img style="width: 100%" src="<?php echo $this->basePath() . '/pictures/products/' . $product['product_picture'];?>" />
        </div>
    </div>
</div>