<div id="content" class="row">
    <div class="desktop-12 mobile-3" id="nav-border"></div>


    <div id="breadcrumb" class="desktop-12">
        <a href="/" class="homepage-link" title="Back to the frontpage">Home</a>


        <span class="separator">»</span>
        <span class="page-title">Skirts</span>


    </div>


    <div id="shopify-section-collection-template" class="shopify-section"><div data-section-id="collection-template">



            <div id="collection-description" class="desktop-12 mobile-3">
                <h1>Skirts</h1>

            </div>

            <div class="clear"></div>




            <div id="sidebar" class="desktop-3 tablet-2 mobile-3">









                <ul class="sortme">
                    <li class="clearfix filter">
                        <h4>Sort</h4>
                        <select id="sort-by" class="styled-select">
                            <option value="manual">Featured</option>
                            <option value="price-ascending">Price, low to high</option>
                            <option value="price-descending">Price, high to low</option>
                            <option value="title-ascending">Alphabetically, A-Z</option>
                            <option value="title-descending">Alphabetically, Z-A</option>
                            <option value="created-ascending">Date, old to new</option>
                            <option value="created-descending">Date, new to old</option>
                            <option value="best-selling">Best Selling</option>
                        </select>
                    </li>
                </ul>
                <script>
                    Shopify.queryParams = {};
                    if (location.search.length) {
                        for (var aKeyValue, i = 0, aCouples = location.search.substr(1).split('&'); i < aCouples.length; i++) {
                            aKeyValue = aCouples[i].split('=');
                            if (aKeyValue.length > 1) {
                                Shopify.queryParams[decodeURIComponent(aKeyValue[0])] = decodeURIComponent(aKeyValue[1]);
                            }
                        }
                    }
                    jQuery('#sort-by')
                        .val('title-ascending')
                        .bind('change', function() {
                            Shopify.queryParams.sort_by = jQuery(this).val();
                            location.search = jQuery.param(Shopify.queryParams);
                        });
                    $(document).on('shopify:section:load', function(event) {
                        jQuery('#sort-by')
                            .val('title-ascending')
                            .bind('change', function() {
                                Shopify.queryParams.sort_by = jQuery(this).val();
                                location.search = jQuery.param(Shopify.queryParams);
                            });
                    });
                </script>
















                <ul class="sortme">
                    <li class="clearfix filter">

                        <h4>Filter by size</h4>
                        <select class="styled-select coll-filter">
                            <option value="">All</option>


                            <option value="s">S</option>



                            <option value="m">M</option>



                            <option value="l">L</option>



                            <option value="xl">XL</option>


                        </select>
                    </li>
                </ul>
                <script>
                    /* Product Tag Filters - Good for any number of filters on any type of collection pages */
                    /* Give you product tag filter select element a class of coll-filter */
                    /* Give your collection select a class of coll-picker */
                    /* Brought to you by Caroline Schnapp */
                    /* Product Tag Filters - Good for any number of filters on any type of collection page.
                     Give you product tag filter select element a class of coll-filter.
                     Give your collection select a class of coll-picker.
                     Brought to you by Caroline Schnapp. */
                    Shopify.queryParams = {};
                    if (location.search.length) {
                        for (var aKeyValue, i = 0, aCouples = location.search.substr(1).split('&'); i < aCouples.length; i++) {
                            aKeyValue = aCouples[i].split('=');
                            if (aKeyValue.length > 1) {
                                Shopify.queryParams[decodeURIComponent(aKeyValue[0])] = decodeURIComponent(aKeyValue[1]);
                            }
                        }
                    }
                    jQuery('.coll-picker').change(function() {
                        if (jQuery(this).val()) {
                            location.href = '/collections/' + jQuery(this).val();
                        }
                        else {
                            location.href = '/collections/all';
                        }
                    });
                    var collFilters = jQuery('.coll-filter');
                    collFilters.change(function() {
                        delete Shopify.queryParams.page;
                        var newTags = [];
                        collFilters.each(function() {
                            if (jQuery(this).val()) {
                                newTags.push(jQuery(this).val());
                            }
                        });

                        var newURL = '/collections/skirts';
                        if (newTags.length) {
                            newURL += '/' + newTags.join('+');
                        }
                        var search = jQuery.param(Shopify.queryParams);
                        if (search.length) {
                            newURL += '?' + search;
                        }
                        location.href = newURL;

                    });

                    $(document).on('shopify:section:load', function(event) {
                        Shopify.queryParams = {};
                        if (location.search.length) {
                            for (var aKeyValue, i = 0, aCouples = location.search.substr(1).split('&'); i < aCouples.length; i++) {
                                aKeyValue = aCouples[i].split('=');
                                if (aKeyValue.length > 1) {
                                    Shopify.queryParams[decodeURIComponent(aKeyValue[0])] = decodeURIComponent(aKeyValue[1]);
                                }
                            }
                        }
                        jQuery('.coll-picker').change(function() {
                            if (jQuery(this).val()) {
                                location.href = '/collections/' + jQuery(this).val();
                            }
                            else {
                                location.href = '/collections/all';
                            }
                        });
                        var collFilters = jQuery('.coll-filter');
                        collFilters.change(function() {
                            delete Shopify.queryParams.page;
                            var newTags = [];
                            collFilters.each(function() {
                                if (jQuery(this).val()) {
                                    newTags.push(jQuery(this).val());
                                }
                            });

                            var newURL = '/collections/skirts';
                            if (newTags.length) {
                                newURL += '/' + newTags.join('+');
                            }
                            var search = jQuery.param(Shopify.queryParams);
                            if (search.length) {
                                newURL += '?' + search;
                            }
                            location.href = newURL;

                        });
                    });
                </script>














                <ul class="sortme">
                    <li class="clearfix filter">

                        <h4>Filter by print</h4>
                        <select class="styled-select coll-filter">
                            <option value="">All</option>


                            <option value="patterns">Patterns</option>



                            <option value="solid">Solid</option>




                        </select>
                    </li>
                </ul>
                <script>
                    /* Product Tag Filters - Good for any number of filters on any type of collection pages */
                    /* Give you product tag filter select element a class of coll-filter */
                    /* Give your collection select a class of coll-picker */
                    /* Brought to you by Caroline Schnapp */
                    /* Product Tag Filters - Good for any number of filters on any type of collection page.
                     Give you product tag filter select element a class of coll-filter.
                     Give your collection select a class of coll-picker.
                     Brought to you by Caroline Schnapp. */
                    Shopify.queryParams = {};
                    if (location.search.length) {
                        for (var aKeyValue, i = 0, aCouples = location.search.substr(1).split('&'); i < aCouples.length; i++) {
                            aKeyValue = aCouples[i].split('=');
                            if (aKeyValue.length > 1) {
                                Shopify.queryParams[decodeURIComponent(aKeyValue[0])] = decodeURIComponent(aKeyValue[1]);
                            }
                        }
                    }
                    jQuery('.coll-picker').change(function() {
                        if (jQuery(this).val()) {
                            location.href = '/collections/' + jQuery(this).val();
                        }
                        else {
                            location.href = '/collections/all';
                        }
                    });
                    var collFilters = jQuery('.coll-filter');
                    collFilters.change(function() {
                        delete Shopify.queryParams.page;
                        var newTags = [];
                        collFilters.each(function() {
                            if (jQuery(this).val()) {
                                newTags.push(jQuery(this).val());
                            }
                        });

                        var newURL = '/collections/skirts';
                        if (newTags.length) {
                            newURL += '/' + newTags.join('+');
                        }
                        var search = jQuery.param(Shopify.queryParams);
                        if (search.length) {
                            newURL += '?' + search;
                        }
                        location.href = newURL;

                    });

                    $(document).on('shopify:section:load', function(event) {
                        Shopify.queryParams = {};
                        if (location.search.length) {
                            for (var aKeyValue, i = 0, aCouples = location.search.substr(1).split('&'); i < aCouples.length; i++) {
                                aKeyValue = aCouples[i].split('=');
                                if (aKeyValue.length > 1) {
                                    Shopify.queryParams[decodeURIComponent(aKeyValue[0])] = decodeURIComponent(aKeyValue[1]);
                                }
                            }
                        }
                        jQuery('.coll-picker').change(function() {
                            if (jQuery(this).val()) {
                                location.href = '/collections/' + jQuery(this).val();
                            }
                            else {
                                location.href = '/collections/all';
                            }
                        });
                        var collFilters = jQuery('.coll-filter');
                        collFilters.change(function() {
                            delete Shopify.queryParams.page;
                            var newTags = [];
                            collFilters.each(function() {
                                if (jQuery(this).val()) {
                                    newTags.push(jQuery(this).val());
                                }
                            });

                            var newURL = '/collections/skirts';
                            if (newTags.length) {
                                newURL += '/' + newTags.join('+');
                            }
                            var search = jQuery.param(Shopify.queryParams);
                            if (search.length) {
                                newURL += '?' + search;
                            }
                            location.href = newURL;

                        });
                    });
                </script>










                <ul>
                    <h4>Explore</h4>

                    <li><a href="/collections/new" title="">New Arrivals</a></li>

                    <li><a href="/collections/dresses" title="">Dresses</a></li>

                    <li><a href="/collections/tops" title="">Tops</a></li>

                    <li><a href="/collections/skirts" title="" class="current">Skirts</a></li>

                    <li><a href="/collections/sale" title="">Sale</a></li>

                </ul>
















                <ul>
                    <label>Shop by Designer</label>

                    <li class="Akris"><a href="/collections/vendors?q=Akris" title="Akris">Akris</a></li>

                    <li class="AZZEDINE ALAÏA"><a href="/collections/vendors?q=AZZEDINE%20ALA%C3%8FA" title="AZZEDINE ALAÏA">AZZEDINE ALAÏA</a></li>

                    <li class="Balenciaga"><a href="/collections/vendors?q=Balenciaga" title="Balenciaga">Balenciaga</a></li>

                    <li class="Chloe"><a href="/collections/vendors?q=Chloe" title="Chloe">Chloe</a></li>

                    <li class="Giambattista Valli"><a href="/collections/vendors?q=Giambattista%20Valli" title="Giambattista Valli">Giambattista Valli</a></li>

                    <li class="Nina Ricci"><a href="/collections/vendors?q=Nina%20Ricci" title="Nina Ricci">Nina Ricci</a></li>

                    <li class="OSMAN YOUSEFZADA"><a href="/collections/vendors?q=OSMAN%20YOUSEFZADA" title="OSMAN YOUSEFZADA">OSMAN YOUSEFZADA</a></li>

                    <li class="PIECE D'ANARCHIVE"><a href="/collections/vendors?q=PIECE%20D%27ANARCHIVE" title="PIECE D'ANARCHIVE">PIECE D'ANARCHIVE</a></li>

                </ul>

















            </div>


            <div class="desktop-9 tablet-4 mobile-3">
                <div id="product-loop">

                    <div class="product-index desktop-4 first tablet-half mobile-half" data-alpha="Boucle Cotton-wool Pencil Skirt" data-price="59000">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018M20700004_3_500x.jpeg?v=1372160276" alt="Boucle Cotton-wool Pencil Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt">

                                <div class="prod-title">Boucle Cotton-wool Pencil Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£590.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt?variant=329614113">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt?variant=329614115">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt?variant=329614117">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/boucle-cotton-wool-pencil-skirt?variant=329614119">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 tablet-half mobile-half" data-alpha="Classic Silk-blend Pencil Skirt" data-price="70500">

                        <div class="so icn">Sold Out</div>

                        <a href="/collections/skirts/products/classic-silk-blend-pencil-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/014P20700002_3_500x.jpeg?v=1372160293" alt="Classic Silk-blend Pencil Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/classic-silk-blend-pencil-skirt">

                                <div class="prod-title">Classic Silk-blend Pencil Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£705.00</span></div>

                            </div>





                        </div>
                    </div>

                    <div class="product-index desktop-4 last tablet-half mobile-half" data-alpha="Cotton Pencil Skirt" data-price="26500">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/cotton-pencil-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/010Q20670003_3.v2_500x.jpeg?v=1372160316" alt="Cotton Pencil Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/cotton-pencil-skirt">

                                <div class="prod-title">Cotton Pencil Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£265.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/cotton-pencil-skirt?variant=329614199">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/cotton-pencil-skirt?variant=329614201">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/cotton-pencil-skirt?variant=329614203">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/cotton-pencil-skirt?variant=329614205">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 first tablet-half mobile-half" data-alpha="Floral Jacquard Cotton-silk Skirt" data-price="27500">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018U20670002_3_500x.jpeg?v=1372160362" alt="Floral Jacquard Cotton-silk Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt">

                                <div class="prod-title">Floral Jacquard Cotton-silk Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£275.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt?variant=329614265">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt?variant=329614267">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt?variant=329614269">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/floral-jacquard-cotton-silk-skirt?variant=329614271">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 tablet-half mobile-half" data-alpha="Folded Crepe Miniskirt" data-price="70000">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/folded-crepe-miniskirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/012N20700002_3_500x.jpeg?v=1372160388" alt="Folded Crepe Miniskirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/folded-crepe-miniskirt">

                                <div class="prod-title">Folded Crepe Miniskirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£700.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/folded-crepe-miniskirt?variant=329614307">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/folded-crepe-miniskirt?variant=329614309">M</a>
                                    </li>








                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 last tablet-half mobile-half" data-alpha="Paisley Jacquard Wool-blend Skirt" data-price="39000">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018U20700002_3_500x.jpeg?v=1372160411" alt="Paisley Jacquard Wool-blend Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt">

                                <div class="prod-title">Paisley Jacquard Wool-blend Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£390.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt?variant=329614337">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt?variant=329614339">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt?variant=329614341">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/paisley-jacquard-wool-blend-skirt?variant=329614343">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 first tablet-half mobile-half" data-alpha="Perforated Stretch Knit Skirt" data-price="0">






                        <a href="/collections/skirts/products/perforated-stretch-knit-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/010520670004_3_500x.jpeg?v=1372160419" alt="Perforated Stretch Knit Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/perforated-stretch-knit-skirt">

                                <div class="prod-title">Perforated Stretch Knit Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£0.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/perforated-stretch-knit-skirt?variant=329614377">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/perforated-stretch-knit-skirt?variant=329614379">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/perforated-stretch-knit-skirt?variant=329614381">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/perforated-stretch-knit-skirt?variant=329614383">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 tablet-half mobile-half" data-alpha="Pleated Jacquard Skirt" data-price="75500">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/pleated-jacquard-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018U20680002_3_500x.jpeg?v=1372160429" alt="Pleated Jacquard Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/pleated-jacquard-skirt">

                                <div class="prod-title">Pleated Jacquard Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£755.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/pleated-jacquard-skirt?variant=329614393">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/pleated-jacquard-skirt?variant=329614395">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/pleated-jacquard-skirt?variant=329614397">L</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 last tablet-half mobile-half" data-alpha="Ribbed Stretch Knit Skirt" data-price="30000">



                        <div class="new icn">New in</div>







                        <div class="sale-item icn">Sale</div>


                        <a href="/collections/skirts/products/ribbed-stretch-knit-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/019820680004_3_500x.jpeg?v=1372160438" alt="Ribbed Stretch Knit Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/ribbed-stretch-knit-skirt">

                                <div class="prod-title">Ribbed Stretch Knit Skirt</div>
                            </a>
                            <div class="price">

                                <div class="onsale"><span class="money">£300.00</span></div>
                                <div class="was"><span class="money">£595.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/ribbed-stretch-knit-skirt?variant=329614405">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/ribbed-stretch-knit-skirt?variant=329614407">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/ribbed-stretch-knit-skirt?variant=329614409">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/ribbed-stretch-knit-skirt?variant=329614411">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 first tablet-half mobile-half" data-alpha="Stretch Jersey Textured Skirt" data-price="35500">

                        <div class="so icn">Sold Out</div>

                        <a href="/collections/skirts/products/stretch-jersey-textured-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018M20670002_3_500x.jpeg?v=1372160481" alt="Stretch Jersey Textured Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/stretch-jersey-textured-skirt">

                                <div class="prod-title">Stretch Jersey Textured Skirt</div>
                            </a>
                            <div class="price">

                                <div class="onsale"><span class="money">£355.00</span></div>
                                <div class="was"><span class="money">£595.00</span></div>

                            </div>





                        </div>
                    </div>

                    <div class="product-index desktop-4 tablet-half mobile-half" data-alpha="Textured Cotton-blend Miniskirt" data-price="81500">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/textured-cotton-blend-miniskirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/011A20680002_3_500x.jpeg?v=1372160524" alt="Textured Cotton-blend Miniskirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/textured-cotton-blend-miniskirt">

                                <div class="prod-title">Textured Cotton-blend Miniskirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£815.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">











                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/textured-cotton-blend-miniskirt?variant=329614735">L</a>
                                    </li>









                                    <li data-option-title="XL" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color xl">
                                        <a href="/collections/skirts/products/textured-cotton-blend-miniskirt?variant=329614737">XL</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                    <div class="product-index desktop-4 last tablet-half mobile-half" data-alpha="Virgin Wool and Stretch Knit Pencil Skirt" data-price="53000">



                        <div class="new icn">New in</div>






                        <a href="/collections/skirts/products/virgin-wool-and-stretch-knit-pencil-skirt">
                            <img src="//cdn.shopify.com/s/files/1/0245/6825/products/018M20700006_3_500x.jpeg?v=1372160534" alt="Virgin Wool and Stretch Knit Pencil Skirt">
                        </a>
                        <div class="product-info">
                            <a href="/collections/skirts/products/virgin-wool-and-stretch-knit-pencil-skirt">

                                <div class="prod-title">Virgin Wool and Stretch Knit Pencil Skirt</div>
                            </a>
                            <div class="price">

                                <div class="prod-price"><span class="money">£530.00</span></div>

                            </div>













                            <div class="size-swatch">
                                <ul data-option-index="0" class="size options">







                                    <li data-option-title="S" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color s">
                                        <a href="/collections/skirts/products/virgin-wool-and-stretch-knit-pencil-skirt?variant=329614741">S</a>
                                    </li>









                                    <li data-option-title="M" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color m">
                                        <a href="/collections/skirts/products/virgin-wool-and-stretch-knit-pencil-skirt?variant=329614743">M</a>
                                    </li>









                                    <li data-option-title="L" data-href="//cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_large.gif" class="color l">
                                        <a href="/collections/skirts/products/virgin-wool-and-stretch-knit-pencil-skirt?variant=329614745">L</a>
                                    </li>




                                </ul>
                            </div><!-- .swatch -->







                        </div>
                    </div>

                </div>
            </div>

            <div id="pagination" class="desktop-12 tablet-6 mobile-3">

                <span class="count">Showing items 1-12 of 12.</span>




            </div>


        </div>


    </div>
</div>