<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<?php echo $this->partial('admin/partial/message'); ?>

<form name="" id="frm" action="<?php echo $this->url('admin/' . $module); ?>" method="post">
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Danh mục</th>
                        <th>Trạng thái</th>
                        <th>Trạng thái</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php  foreach ($records as $k => $v) { ?>
                        <tr>
                            <td colspan="3"><?php echo $k;?></td>
                        </tr>
                        <?php $stt = 1; foreach ($v['category'] as $kk => $vv) { ?>
                            <tr>
                                <td><?php echo $kk; ?></td>
                                <td><?php echo $vv[1]; ?></td>
                                <td class="loading">
                                    <input id="btn-get-post-<?php echo $stt;?>" type="button" onclick="getPostItem(<?php echo $stt;?>)" class="btn btn-primary" value="Lấy tin">
                                    <input type="hidden" class="post_item" id="post_item_<?php echo $stt;?>" href="javascript:void(0);" data-domain="<?php echo $k;?>" data-url="<?php echo $vv[1];?>" data-category="<?php echo $vv[0];?>" />
                                    <div></div>
                                </td>
                            </tr>
                            <?php $stt++; } ?>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <input id="btn-get-post" type="button" onclick="getPost()" class="btn btn-primary" value="Lấy tin">
                </div>

            </div>
        </div>
    </div>
</div>
</form>

<script>
    var st = 1;

    function getPost()
    {
        $('#btn-get-post').attr('disabled', 'disabled');

        if ($('#post_item_' + st).length > 0) {

            var _this = $('#post_item_' + st);

            var domain      = $(_this).attr('data-domain');
            var url         = $(_this).attr('data-url');
            var category    = $(_this).attr('data-category');

            _this.next().html('Loading');

            $.ajax({
                url: '<?php echo $this->url('admin/post-get', array('action' => 'outsite'));?>',
                type: 'post',
                data: {domain: domain, url: url, category: category},
                async: true,
                success: function (response) {
                    _this.next().html('');
                    st++;
                    getPost();
                },
                error: function() {
                    _this.next().html('<span class="label label-danger">Error</span>                                                ');
                    st++;
                    getPost();
                }
            });
        } else {
            $('#btn-get-post').removeAttr('disabled');
        }
    }

    function getPostItem(stt)
    {
        $('#btn-get-post-'+stt).attr('disabled', 'disabled');

        if ($('#post_item_' + stt).length > 0) {

            var _this = $('#post_item_' + stt);

            var domain      = $(_this).attr('data-domain');
            var url         = $(_this).attr('data-url');
            var category    = $(_this).attr('data-category');

            _this.next().html('Loading');

            $.ajax({
                url: '<?php echo $this->url('admin/post-get', array('action' => 'outsite'));?>',
                type: 'post',
                data: {domain: domain, url: url, category: category},
                async: true,
                success: function (response) {
                    _this.next().html('');
                },
                error: function() {
                    _this.next().html('<span class="label label-danger">Error</span>                                                ');
                }
            });
        } else {
            $('#btn-get-post-'+stt).removeAttr('disabled');
        }
    }
</script>