<div class="form-actions" style="margin-top: 0; padding-top: 0; padding-bottom: 0">
    <select id="list_action" style="float: left; margin-right: 10px;" class="input-small valid">
        <option value="">Thao tác</option>
        <option value="delete">Xóa</option>
    </select>
    <input id="btn-action-list" type="button" class="btn btn-primary ui-wizard-content ui-formwizard-button" value="Thực hiện" style="float: left;">
</div>