<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<?php echo $this->partial('admin/partial/button_add', array('moduleName' => $module)); ?>

<?php echo $this->partial('admin/partial/message'); ?>

<form name="" id="frm" action="<?php echo $this->url('admin/' . $module); ?>" method="post">
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th><input type="checkbox" class="checkbox-all" /></th>
                        <th>Group</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr style="background: <?php echo $statusColor[$record['status']]; ?>">
                            <td><input type="checkbox" class="checkbox-item" name="check_item[]" value="<?php echo $record['group_admin_id']; ?>" /></td>
                            <td><strong><?php echo $this->escapeHtml($record['group_admin_name']); ?></strong></td>
                            <td><?php echo $status[$record['group_admin_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/' . $module, array('action' => 'edit'), array('query' => array('id' => $record['group_admin_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a href="<?php echo $this->url('admin/' . $module, array('action' => 'acl'), array('query' => array('id' => $record['group_admin_id']))); ?>">
                                    <i class="icon-user"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/' . $module, array('action' => 'delete'), array('query' => array('id' => $record['group_admin_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/' . $module),)); ?>
            </div>
        </div>
    </div>
</div>
</form>

<?php echo $this->partial('admin/partial/action_list'); ?>