<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3><i class="icon-edit"></i> <?php echo $actionTitle;?></h3>
            </div>
            <div class="box-content nopadding">
                <?php
                $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-bordered', 'id' => 'frm']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('news_category_id')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('news_category_id')); ?>
                        <?php echo $this->formElementErrors($form->get('news_category_id'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                    <div class="control-group">
                        <?php echo $this->formLabel($form->get('news_title')); ?>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('news_title')); ?>
                            <?php echo $this->formElementErrors($form->get('news_title'), array('class' => 'error-message')); ?>
                        </div>
                    </div>


                <div class="control-group">
                    <?php echo $this->formLabel($form->get('news_picture')); ?>
                    <div class="controls">


                        <?php echo $this->formElementErrors($form->get('news_picture'), array('class' => 'error-message')); ?>

                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 50px; height: 50px;">
                                <?php if (isset($record) && $record['news_picture'] != '') {?>
                                    <img title="Click để xóa" id="picture" onclick="deletePicture(<?php echo $record['news_id'];?>)" style="width: 50px; height: 50px; cursor: pointer" class="img-thumbnail" src="<?php echo $this->basePath('pictures/news/' . $record['news_picture']);?>" />
                                <?php } else {?>
                                    <img src="<?php echo $this->basePath('pictures/no-image.gif');?>" class="img-thumbnail" style="width: 50px; height: 50px" />
                                <?php }?>
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div>
                            <div>
                                <span class="btn btn-file">
                                    <span class="fileupload-new">Chọn hình</span><span class="fileupload-exists">Thay đổi</span>
                                    <?php echo $this->formElement($form->get('news_picture')); ?></span>
                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Xóa</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="control-group">
                   <?php echo $this->formLabel($form->get('news_quote')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('news_quote')); ?>
                        <?php echo $this->formElementErrors($form->get('news_quote'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                    <div class="control-group">
                        <?php echo $this->formLabel($form->get('news_content')); ?>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('news_content')); ?>
                            <?php echo $this->formElementErrors($form->get('news_content'), array('class' => 'error-message')); ?>
                        </div>
                    </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('news_status')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('news_status')); ?>
                        <?php echo $this->formElementErrors($form->get('news_status'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label col-lg-2" for="page_title">Url</label>
                    <div class="controls">
                        <strong><?php echo trim($this->url('home-news-detail', array('name' => $this->functions()->formatTitle($record['news_title']), 'id' => $record['news_id'])), '/');?></strong>
                    </div>
                </div>

                    <div class="form-actions">
                        <input type="button" onclick="location.href='<?php echo $this->url('admin/' . $module);?>'" name="back" id="back" class="btn btn-default" value="Quay lại">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->formHidden($form->get('csrf')); ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $("#frm").validate({
            rules: {
                news_title: 'required',
            },
            messages: {
                news_title: 'Vui lòng nhập thông tin',
            }
        });
    });

    function deletePicture(id) {
        if (confirm('Bạn có muốn xóa?')) {
            $.ajax({
                url: '<?php echo $this->url('admin/news', array('action' => 'delete-picture'));?>',
                type: 'post',
                data: {id: id},
                success: function (response) {
                    data = jQuery.parseJSON(response);
                    if (data.return == 1) {
                        $('#picture').remove();
                    }
                }
            });
        }
    }
</script>