<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<?php echo $this->partial('admin/partial/message'); ?>

<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color box-search">
            <div class="box-title">
                <h3><i class="icon-th-list"></i> Tìm kiếm</h3>
            </div>
            <div class="box-content nopadding">
                <form action="#" method="POST" class="form-horizontal form-column">
                    <div class="span6">
                        <div class="control-group">
                            <label for="textfield" class="control-label">Tiêu đề</label>

                            <div class="controls">
                                <input type="text" name="name" id="name" class="input-xlarge"
                                       value="<?php echo $search['name']; ?>">
                            </div>
                        </div>

                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <label for="textfield" class="control-label">Danh mục</label>

                            <div class="controls">
                                <select name="category" class="input-xlarge">
                                    <option value="">Tất cả</option>
                                    <?php foreach ($newsCategory as $v) { ?>
                                        <option <?php echo ($v['news_category_id'] == $search['category']) ? 'selected="selected"' : ''; ?>
                                            value="<?php echo $v['news_category_id']; ?>"><?php echo $v['news_category_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="span12">
                        <div class="form-actions text-right" style="margin-top: 0; margin-bottom: 0; padding-top: 0">
                            <button type="submit" class="btn btn-primary">Tìm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<br>

<?php echo $this->partial('admin/partial/button_add', array('moduleName' => $module)); ?>

<form name="" id="frm" action="<?php echo $this->url('admin/' . $module); ?>" method="post">
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th><input type="checkbox" class="checkbox-all" /></th>
                        <th>Tiêu đề</th>
                        <th>Danh mục</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr style="background: <?php echo $statusColor[$record['status']]; ?>">
                            <td><input type="checkbox" class="checkbox-item" name="check_item[]" value="<?php echo $record['news_id']; ?>" /></td>
                            <td><strong><?php echo $this->escapeHtml($record['news_title']); ?></strong></td>
                            <td><?php echo $this->escapeHtml($record['news_category_name']); ?></td>
                            <td><?php echo $status[$record['news_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/' . $module, array('action' => 'edit'), array('query' => array('id' => $record['news_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/' . $module, array('action' => 'delete'), array('query' => array('id' => $record['news_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/' . $module),)); ?>
                </div>

            </div>
        </div>
    </div>
</div>
</form>

<?php echo $this->partial('admin/partial/action_list'); ?>
