<?php echo $this->partial('admin/partial/title', array('moduleTitle' => $title)); ?>

<?php echo $this->partial('admin/partial/button_add', array('moduleName' => $module, 'urlOther' => $this->url('admin/' . $module, array('action' => 'add'), array('query' => array('group_navigation_id' => $_GET['group_navigation_id']))))); ?>

<?php echo $this->partial('admin/partial/message'); ?>

    <div class="box">
        <div class="box-title">
            <h3><i class="icon-edit"></i> <?php echo $groupNavigation['group_navigation_name']; ?></h3>
        </div>
    </div>

<form name="" id="frm" action="<?php echo $this->url('admin/' . $module); ?>" method="post">
    <input type="hidden" name="group_navigation_id" value="<?php echo $_GET['group_navigation_id'];?>">
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive scroll-div">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th><input type="checkbox" class="checkbox-all" /></th>
                        <th>Liên kết</th>
                        <th>Liên kết đến</th>
                        <th>Thứ tự</th>
                        <th>Menu</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr>
                            <td><input type="checkbox" class="checkbox-item" name="check_item[]" value="<?php echo $record['navigation_id']; ?>" /></td>
                            <td><strong><?php echo str_repeat('__', $record['navigation_level']) . ' ' . $this->escapeHtml($record['navigation_name']); ?></strong></td>
                            <td><?php echo ($record['navigation_url_select'] != '') ? $this->escapeHtml($record['navigation_url_select']) : $this->escapeHtml($record['navigation_url']); ?></></td>
                            <td><?php echo $record['navigation_position']; ?></td>
                            <td><strong><?php echo $this->escapeHtml($record['group_navigation_name']); ?></strong></td>
                            <td><?php echo $status[$record['navigation_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/' . $module, array('action' => 'edit'), array('query' => array('id' => $record['navigation_id'], 'group_navigation_id' => $_GET['group_navigation_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/' . $module, array('action' => 'delete'), array('query' => array('id' => $record['navigation_id'], 'group_navigation_id' => $_GET['group_navigation_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</form>

<?php echo $this->partial('admin/partial/action_list'); ?>