<a class="btn btn-default" href="<?php echo $this->url('home-structure');?>" role="button">Quay lại</a> <a class="btn btn-primary" href="<?php echo $this->url('home-structure-process');?>" role="button">Tiếp tục</a>

<table class="table table-bordered" style="margin-top: 10px;">
    <thead>

    <tr>
        <th>#</th>
        <th>Tiếng Việt</th>
        <th>Tiếng Anh</th>
    </tr>

    </thead>
    <tbody>
    <?php $stt = 1; foreach($records as $v) {?>
    <tr>
        <th scope="row"><?php echo $stt;?></th>
        <td><?php echo $v['structure_vn'];?></td>
        <td><?php echo $v['structure_en'];?></td>
    </tr>
    <?php $stt++; }?>

    </tbody>
</table>