<?php
$dataCurrent = current($records);
?>

<form method="post">
    <div class="form-group">
        <label><?php echo $dataCurrent['structure_vn'];?></label>


        <input autofocus style="<?php if ($message != '') {?>border: 1px solid #a94442<?php }?>" type="text" class="form-control" name="structure_en">

        <?php if ($message != '') {?>
            <p class="text-danger"><?php echo $message;?></p>
        <?php }?>

        <input type="hidden" name="id" value="<?php echo $dataCurrent['structure_id'];?>">
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        Gợi ý
    </button>

    <button type="submit" class="btn btn-success">Tiếp tục</button>
</form>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <?php echo $dataCurrent['structure_en'];?>
            </div>
        </div>
    </div>
</div>