<div class="desktop-12 mobile-3" id="nav-border"></div>
<?php echo $breadcrumbs; ?>
<div id="page" class="desktop-12 tablet-6 mobile-3 page-template" data-section-id="">

    <h1><?php echo $this->escapeHtml($newsCategory['news_category_name']); ?></h1>

    <ul id="featured-posts">
        <?php echo $this->partial('home/partial/blog-item', array('news' => $news)); ?>
    </ul>
    <?php echo $this->paginationControl($news, 'sliding', 'home/partial/paginator', array('url' => $this->url('home-news-category', array('name' => $name, 'id' => $id)))); ?>
</div>
