<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title"><?php echo $this->escapeHtml($newsCategory['news_category_name']);?></h3></div>
        <div class="panel-body">
            <h4 style="color: #0067bf"><strong><?php echo $this->escapeHtml($news['news_title']);?></strong></h4>

            <div class="rte">
                <?php echo $news['news_content'];?>
            </div>

        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Liên quan</h3></div>
        <div class="panel-body">
            <div class="list-group news-other">
                <?php foreach($newsOther as $v) {?>
                    <a href="<?php echo $this->url('home-news-detail', array('name' => $this->functions()->formatTitle($v['news_title']), 'id' => $v['news_id']));?>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> <?php echo $this->escapeHtml($v['news_title']);?></a>
                <?php }?>
            </div>
        </div>
    </div>
</div>

