
<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Liên hệ</h3></div>
        <div class="panel-body ">

            <div class="col-md-12">
                <?php echo $templateData[16]['template_content']; ?>
            </div>

            <div class="col-md-6 contact">
                <?php
                $form->setAttributes(['action' => '', 'class' => 'contact-form', 'id' => 'contact_form']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('contact_fullname')); ?>
                    <?php echo $this->formElement($form->get('contact_fullname')); ?>
                    <?php echo $this->formElementErrors($form->get('contact_fullname'), array('class' => 'error-message')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('contact_email')); ?>
                    <?php echo $this->formElement($form->get('contact_email')); ?>
                    <?php echo $this->formElementErrors($form->get('contact_email'), array('class' => 'error-message')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('contact_phone')); ?>
                    <?php echo $this->formElement($form->get('contact_phone')); ?>
                    <?php echo $this->formElementErrors($form->get('contact_phone'), array('class' => 'error-message')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formLabel($form->get('contact_content')); ?>
                    <?php echo $this->formElement($form->get('contact_content')); ?>
                    <?php echo $this->formElementErrors($form->get('contact_content'), array('class' => 'error-message')); ?>
                </div>

                <div class="form-group captcha">
                    <?php echo $this->formRow($form->get('Captcha'));?>
                    <?php echo $this->formElementerrors($form->get('Captcha'), ['class' => 'error-message']); ?>
                </div>


                <?php echo $this->formSubmit($form->get('submit')); ?>
                <?php echo $this->formHidden($form->get('csrf')); ?>

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function() {
        $('input[name="captcha[input]"]').addClass('form-control input-captcha');

        $("#contact_form").validate({
            rules: {
                contact_fullname: 'required',
                contact_phone: {
                    required: true,
                    number: true,
                },
                contact_email: {
                    required: true,
                    email: true,
                },
                contact_content: {
                    required: true,
                    maxlength: 300,
                },
            },
            messages: {
                contact_fullname: 'Vui lòng nhập thông tin',
                contact_phone: {
                    required: 'Vui lòng nhập thông tin',
                    number: 'Thông tin không đúng định dạng',
                },
                contact_email: {
                    required: 'Vui lòng nhập thông tin',
                    email: 'Thông tin không đúng định dạng',
                },
                contact_content: {
                    required: 'Vui lòng nhập thông tin',
                    maxlength: 'Lời nhắn không quá 300 ký tự',
                },
            }
        });

        $('div.captcha img').click(function(){
            $.get('<?php echo $this->url('captcha');?>', function(data) {
                $('div.captcha img').attr('src', data.url);
                $('input[name="Captcha[id]"]').val(data.id);
            });
        });
    });
</script>