<div class="desktop-12 mobile-3" id="nav-border"></div>
<?php echo $breadcrumbs; ?>

<div id="page" class="desktop-12 tablet-6 mobile-3">
    <h1>Liên hệ</h1>
</div>

<div class="desktop-6 tablet-6 mobile-3">
    <p>Cám ơn Bạn đã liên hệ với Kaylee.vn.<br>
    Mọi thắc mắc của bạn sẽ được tư vấn trong thời gian sớm nhất.<br> Nhấn vào <a style="text-decoration: underline" href="<?php echo $this->url('home');?>">đây</a> để trở về trang chủ.</p>
</div>