<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Liên hệ</h3></div>
        <div class="panel-body ">

            <div class="col-md-12">
                <?php echo $templateData[16]['template_content']; ?>
            </div>

            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
            <p>Cám ơn Bạn đã liên hệ với chúng tôi.<br>
                Mọi thắc mắc của bạn sẽ được tư vấn trong thời gian sớm nhất.<br> Nhấn vào <a style="text-decoration: underline" href="<?php echo $this->url('home');?>">đây</a> để trở về trang chủ.</p>
                    </div>
            </div>
        </div>
    </div>
</div>