<div class="page-header" style="margin-top: 0">
    <div class="pull-left">
        <h1>CMS</h1>
    </div>
    <!--    <div class="pull-right">-->
    <!--        <ul class="stats">-->
    <!--            <li class="blue">-->
    <!--                <i class="icon-shopping-cart"></i>-->
    <!--                <div class="details">-->
    <!--                    <span class="big">172</span>-->
    <!--                    <span>New orders</span>-->
    <!--                </div>-->
    <!--            </li>-->
    <!--            <li class="green">-->
    <!--                <i class="icon-money"></i>-->
    <!--                <div class="details">-->
    <!--                    <span class="big">$325,12</span>-->
    <!--                    <span>Balance</span>-->
    <!--                </div>-->
    <!--            </li>-->
    <!--            <li class="orange">-->
    <!--                <i class="icon-calendar"></i>-->
    <!--                <div class="details">-->
    <!--                    <span class="big">April 1, 2017</span>-->
    <!--                    <span>Saturday, 20:07</span>-->
    <!--                </div>-->
    <!--            </li>-->
    <!--        </ul>-->
    <!--    </div>-->
</div>
